import puppeteer from 'puppeteer-core';
import { readFileSync } from 'fs';
const title = readFileSync('naver_symphony_title.txt','utf8').trim();
const body = readFileSync('naver_symphony_body.txt','utf8');
const browser = await puppeteer.connect({ browserURL:'http://127.0.0.1:9222' });
const pages = await browser.pages();
let page = pages.find(p => p.url().includes('blog.naver.com') && p.url().includes('Redirect=Write'));
if (!page) throw new Error('write page not found');
await page.bringToFront();
await new Promise(r=>setTimeout(r,1000));
const result = await page.evaluate(({title, body}) => {
  const w = document.querySelector('iframe#mainFrame')?.contentWindow || window;
  const ed = w.SmartEditor?._editors?.blogpc001;
  if (!ed) return {error:'SmartEditor not found'};
  const data = ed.getDocumentData();
  const uuid = () => 'SE-' + crypto.randomUUID();
  const cleanText = v => String(v ?? '').replace(/[\u0000-\u0008\u000B\u000C\u000E-\u001F\u007F]/g,'').trim();
  const para = value => ({id:uuid(), nodes:[{id:uuid(), value:cleanText(value), '@ctype':'textNode'}], '@ctype':'paragraph'});
  const titleComp = data.document.components.find(c => c['@ctype']==='documentTitle') || {'@ctype':'documentTitle'};
  titleComp.title = [para(title)];
  const paras = body.split(/\n\n+/).map(s=>s.trim()).filter(Boolean);
  const textComp = {id:uuid(), layout:'default', value:paras.map(para), '@ctype':'text'};
  data.document.components = [titleComp, textComp];
  ed.setDocumentData(data);
  const txt = ed.getContentText();
  return {title:ed.getDocumentTitle(), textLen:txt.length, hasMarkdownHeading:/(^|\n)#{1,6}\s/.test(txt), hasFence:txt.includes('```'), hasCodeMarker:txt.includes('【코드'), start:txt.slice(0,120)};
}, {title, body});
console.log(JSON.stringify(result,null,2));
await page.screenshot({path:'symphony-injected.png', fullPage:false});
await browser.disconnect();
